/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cursoemvideo;

import java.awt.Font;

/**
 *
 * @author nti
 */
public class AdivinhaGenio extends javax.swing.JFrame {

    /**
     * Creates new form AdivinhaGenio
     */
    public AdivinhaGenio() {
        initComponents();
        
        lblFrase.setText("<html>Vou pensar em um valor de 1 à 5. Tente adivinhar!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrase = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPalpte = new javax.swing.JSpinner();
        btnAdivinha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblFrase.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("ESCOLHA UM NUMERO DE 1 A 5 ");
        lblFrase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblFrase);
        lblFrase.setBounds(10, 50, 240, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cursoemvideo/imgs/02a4a086dd6d2db1a4a158f33ce9c292.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 264, 191);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cursoemvideo/imgs/download.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 190, 189, 267);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Valor:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 50, 20);

        txtPalpte.setFont(new java.awt.Font("Segoe UI Light", 1, 13)); // NOI18N
        txtPalpte.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtPalpte);
        txtPalpte.setBounds(60, 210, 70, 30);

        btnAdivinha.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAdivinha.setText("Adivinhar");
        btnAdivinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdivinha);
        btnAdivinha.setBounds(30, 260, 100, 50);

        setSize(new java.awt.Dimension(387, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdivinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinhaActionPerformed
        // TODO add your handling code here:
        double numeroGenio  = 1 + Math.random() * (6-1);
        int valor = (int) numeroGenio;
        System.out.println(valor);
        
        int num = Integer.parseInt(txtPalpte.getValue().toString());
        
        String f1 = "<html>ACERTOU !!!</html>";
        String f2 = "<html>ERROU Eu pensei no valor: </html>"+ valor;
        
        if(valor == num){
            lblFrase.setText(f1);
        }
        else{
            
            //lblFrase.setFont(new Font("Arial Red", Font.PLAIN 16));
            lblFrase.setText(f2);
        }
        
        
        
        
    }//GEN-LAST:event_btnAdivinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdivinhaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdivinhaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdivinhaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdivinhaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdivinhaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdivinha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JSpinner txtPalpte;
    // End of variables declaration//GEN-END:variables
}
